LOCK TABLES `employee` WRITE;
/*!40000 ALTER TABLE `employee` DISABLE KEYS */;

INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (1, 'Josephine', 'Njoroge', 'jnjoroge96@siwakadishes.co.ke', 3, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (2, 'Kwame', 'Osman', 'kosman99@siwakadishes.co.ke', 10, 'Cook');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (3, 'Emmanuelle', 'Munyui', 'emunyui58@siwakadishes.co.ke', 5, 'Assistant Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (4, 'Lerato', 'Wanyama', 'lwanyama62@siwakadishes.co.ke', 2, 'Receptionist');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (5, 'Patricia', 'Malema', 'pmalema40@siwakadishes.co.ke', 8, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (6, 'Patricia', 'Mutombo', 'pmutombo16@siwakadishes.co.ke', 4, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (7, 'Adebayo', 'Kabongo', 'akabongo69@siwakadishes.co.ke', 10, 'Cook');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (8, 'Marie', 'Lumumba', 'mlumumba47@siwakadishes.co.ke', 1, 'Sous Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (9, 'Alaine', 'Malema', 'amalema88@siwakadishes.co.ke', 4, 'Waiter');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (10, 'Jeanne', 'Njoroge', 'jnjoroge41@siwakadishes.co.ke', 10, 'Receptionist');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (11, 'Michel', 'Abdullahi', 'mabdullahi64@siwakadishes.co.ke', 9, 'Bartender');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (12, 'Kwame', 'Kiplagat', 'kkiplagat86@siwakadishes.co.ke', 3, 'Host');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (13, 'Lerato', 'Munzala', 'lmunzala42@siwakadishes.co.ke', 9, 'Security Guard');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (14, 'Thabo', 'Kabila', 'tkabila6@siwakadishes.co.ke', 3, 'Receptionist');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (15, 'Claudine', 'Munyoki', 'cmunyoki42@siwakadishes.co.ke', 3, 'Cook');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (16, 'Pauline', 'Munee', 'pmunee80@siwakadishes.co.ke', 1, 'Waiter');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (17, 'Josephine', 'Odhiambo', 'jodhiambo85@siwakadishes.co.ke', 4, 'Assistant Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (18, 'Adebayo', 'Hussein', 'ahussein90@siwakadishes.co.ke', 5, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (19, 'Gbemisola', 'Lumumba', 'glumumba23@siwakadishes.co.ke', 4, 'Waitress');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (20, 'Alaine', 'Munzala', 'amunzala73@siwakadishes.co.ke', 5, 'Receptionist');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (21, 'Mwangi', 'Kabongo', 'mkabongo82@siwakadishes.co.ke', 1, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (22, 'Gbemisola', 'Kabila', 'gkabila26@siwakadishes.co.ke', 7, 'Sous Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (23, 'Ifeanyi', 'Hassan', 'ihassan31@siwakadishes.co.ke', 6, 'Bartender');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (24, 'Kiptoo', 'Mandela', 'kmandela21@siwakadishes.co.ke', 7, 'Security Guard');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (25, 'Michel', 'Osman', 'mosman56@siwakadishes.co.ke', 8, 'Assistant Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (26, 'Kofi', 'Osman', 'kosman27@siwakadishes.co.ke', 9, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (27, 'Fatou', 'Mbeki', 'fmbeki89@siwakadishes.co.ke', 7, 'Host');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (28, 'Jacqueline', 'Ndayishimiye', 'jndayishimiye20@siwakadishes.co.ke', 5, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (29, 'Felix', 'Munzala', 'fmunzala31@siwakadishes.co.ke', 4, 'Receptionist');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (30, 'Pierrette', 'Njoroge', 'pnjoroge43@siwakadishes.co.ke', 9, 'Sous Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (31, 'Zanele', 'Ibrahim', 'zibrahim55@siwakadishes.co.ke', 10, 'Host');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (32, 'Pierrette', 'Njoroge', 'pnjoroge21@siwakadishes.co.ke', 9, 'Security Guard');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (33, 'Emmanuelle', 'Mugisha', 'emugisha84@siwakadishes.co.ke', 2, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (34, 'Emmanuelle', 'Ibrahim', 'eibrahim83@siwakadishes.co.ke', 3, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (35, 'Chinua', 'Abdi', 'cabdi67@siwakadishes.co.ke', 2, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (36, 'Otieno', 'Njoroge', 'onjoroge85@siwakadishes.co.ke', 10, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (37, 'Joseph', 'Mbeki', 'jmbeki92@siwakadishes.co.ke', 6, 'Receptionist');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (38, 'Michelle', 'Odhiambo', 'modhiambo52@siwakadishes.co.ke', 6, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (39, 'Ifeanyi', 'Abdullahi', 'iabdullahi42@siwakadishes.co.ke', 1, 'Hostess');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (40, 'Mwangi', 'Munywe', 'mmunywe85@siwakadishes.co.ke', 2, 'Sous Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (41, 'Chiamaka', 'Ahmed', 'cahmed91@siwakadishes.co.ke', 8, 'Host');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (42, 'Chiamaka', 'Munzala', 'cmunzala69@siwakadishes.co.ke', 3, 'Bartender');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (43, 'Femi', 'Mutua', 'fmutua34@siwakadishes.co.ke', 9, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (44, 'Alaine', 'Munzala', 'amunzala80@siwakadishes.co.ke', 3, 'Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (45, 'Zanele', 'Mukasa', 'zmukasa98@siwakadishes.co.ke', 5, 'Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (46, 'Bongani', 'Mwangi', 'bmwangi76@siwakadishes.co.ke', 7, 'Hostess');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (47, 'Patrick', 'Omondi', 'pomondi87@siwakadishes.co.ke', 8, 'Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (48, 'Fatou', 'Zuma', 'fzuma50@siwakadishes.co.ke', 5, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (49, 'Patricia', 'Hassan', 'phassan5@siwakadishes.co.ke', 8, 'Cook');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (50, 'Gbemisola', 'Mandela', 'gmandela24@siwakadishes.co.ke', 2, 'Hostess');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (51, 'Jelani', 'Munzala', 'jmunzala6@siwakadishes.co.ke', 9, 'Security Guard');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (52, 'Jelani', 'Abdi', 'jabdi55@siwakadishes.co.ke', 9, 'Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (53, 'Pierrette', 'Njoroge', 'pnjoroge47@siwakadishes.co.ke', 8, 'Hostess');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (54, 'Gbemisola', 'Hussein', 'ghussein89@siwakadishes.co.ke', 1, 'Hostess');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (55, 'Binta', 'Munzala', 'bmunzala96@siwakadishes.co.ke', 6, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (56, 'Felicite', 'Lumumba', 'flumumba97@siwakadishes.co.ke', 8, 'Cook');
UPDATE siwaka_dishes.employee SET reportsTo = 44 WHERE employeeNumber = 8;
UPDATE siwaka_dishes.employee SET reportsTo = 30 WHERE employeeNumber = 16;
UPDATE siwaka_dishes.employee SET reportsTo = 44 WHERE employeeNumber = 21;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 39;
UPDATE siwaka_dishes.employee SET reportsTo = 44 WHERE employeeNumber = 54;
UPDATE siwaka_dishes.employee SET reportsTo = 17 WHERE employeeNumber = 4;
UPDATE siwaka_dishes.employee SET reportsTo = 3 WHERE employeeNumber = 33;
UPDATE siwaka_dishes.employee SET reportsTo = 40 WHERE employeeNumber = 35;
UPDATE siwaka_dishes.employee SET reportsTo = 44 WHERE employeeNumber = 40;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 50;
UPDATE siwaka_dishes.employee SET reportsTo = 17 WHERE employeeNumber = 1;
UPDATE siwaka_dishes.employee SET reportsTo = 52 WHERE employeeNumber = 12;
UPDATE siwaka_dishes.employee SET reportsTo = 52 WHERE employeeNumber = 14;
UPDATE siwaka_dishes.employee SET reportsTo = 30 WHERE employeeNumber = 15;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 34;
UPDATE siwaka_dishes.employee SET reportsTo = 52 WHERE employeeNumber = 42;
UPDATE siwaka_dishes.employee SET reportsTo = 44 WHERE employeeNumber = 44;
UPDATE siwaka_dishes.employee SET reportsTo = 17 WHERE employeeNumber = 6;
UPDATE siwaka_dishes.employee SET reportsTo = 40 WHERE employeeNumber = 9;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 17;
UPDATE siwaka_dishes.employee SET reportsTo = 30 WHERE employeeNumber = 19;
UPDATE siwaka_dishes.employee SET reportsTo = 8 WHERE employeeNumber = 29;
UPDATE siwaka_dishes.employee SET reportsTo = 25 WHERE employeeNumber = 3;
UPDATE siwaka_dishes.employee SET reportsTo = 40 WHERE employeeNumber = 18;
UPDATE siwaka_dishes.employee SET reportsTo = 44 WHERE employeeNumber = 20;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 28;
UPDATE siwaka_dishes.employee SET reportsTo = 40 WHERE employeeNumber = 45;
UPDATE siwaka_dishes.employee SET reportsTo = 44 WHERE employeeNumber = 48;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 23;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 37;
UPDATE siwaka_dishes.employee SET reportsTo = 3 WHERE employeeNumber = 38;
UPDATE siwaka_dishes.employee SET reportsTo = 3 WHERE employeeNumber = 55;
UPDATE siwaka_dishes.employee SET reportsTo = 40 WHERE employeeNumber = 22;
UPDATE siwaka_dishes.employee SET reportsTo = 8 WHERE employeeNumber = 24;
UPDATE siwaka_dishes.employee SET reportsTo = 30 WHERE employeeNumber = 27;
UPDATE siwaka_dishes.employee SET reportsTo = 44 WHERE employeeNumber = 46;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 5;
UPDATE siwaka_dishes.employee SET reportsTo = 22 WHERE employeeNumber = 25;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 41;
UPDATE siwaka_dishes.employee SET reportsTo = 3 WHERE employeeNumber = 47;
UPDATE siwaka_dishes.employee SET reportsTo = 30 WHERE employeeNumber = 49;
UPDATE siwaka_dishes.employee SET reportsTo = 25 WHERE employeeNumber = 53;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 56;
UPDATE siwaka_dishes.employee SET reportsTo = 25 WHERE employeeNumber = 11;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 13;
UPDATE siwaka_dishes.employee SET reportsTo = 40 WHERE employeeNumber = 26;
UPDATE siwaka_dishes.employee SET reportsTo = 44 WHERE employeeNumber = 30;
UPDATE siwaka_dishes.employee SET reportsTo = 52 WHERE employeeNumber = 32;
UPDATE siwaka_dishes.employee SET reportsTo = 30 WHERE employeeNumber = 43;
UPDATE siwaka_dishes.employee SET reportsTo = 22 WHERE employeeNumber = 51;
UPDATE siwaka_dishes.employee SET reportsTo = 25 WHERE employeeNumber = 52;
UPDATE siwaka_dishes.employee SET reportsTo = 25 WHERE employeeNumber = 2;
UPDATE siwaka_dishes.employee SET reportsTo = 3 WHERE employeeNumber = 7;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 10;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 31;
UPDATE siwaka_dishes.employee SET reportsTo = 17 WHERE employeeNumber = 36;
/*!40000 ALTER TABLE `employee` ENABLE KEYS */;
UNLOCK TABLES;