USE `siwaka_dishes`;

LOCK TABLES `employee` WRITE;
/*!40000 ALTER TABLE `employee` DISABLE KEYS */;

INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (1, 'Hawa', 'Mbeki', 'hmbeki71@siwakadishes.co.ke', 9, 'Host');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (2, 'Claude', 'Mohammed', 'cmohammed18@siwakadishes.co.ke', 7, 'Waitress');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (3, 'Chiamaka', 'Munzala', 'cmunzala35@siwakadishes.co.ke', 3, 'Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (4, 'Jelani', 'Lumumba', 'jlumumba64@siwakadishes.co.ke', 1, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (5, 'Kofi', 'Zuma', 'kzuma39@siwakadishes.co.ke', 9, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (6, 'Achieng', 'Kagame', 'akagame27@siwakadishes.co.ke', 4, 'Waiter');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (7, 'Dayo', 'Munyui', 'dmunyui40@siwakadishes.co.ke', 2, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (8, 'Pierre', 'Mutua', 'pmutua19@siwakadishes.co.ke', 6, 'Cook');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (9, 'Ifeanyi', 'Kabongo', 'ikabongo54@siwakadishes.co.ke', 1, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (10, 'Binta', 'Wanyama', 'bwanyama22@siwakadishes.co.ke', 5, 'Bartender');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (11, 'Hawa', 'Mbeki', 'hmbeki61@siwakadishes.co.ke', 6, 'Security Guard');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (12, 'Emmanuelle', 'Abdullahi', 'eabdullahi85@siwakadishes.co.ke', 4, 'Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (13, 'Zanele', 'Hussein', 'zhussein58@siwakadishes.co.ke', 9, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (14, 'Jacques', 'Kabongo', 'jkabongo90@siwakadishes.co.ke', 2, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (15, 'Patrick', 'Munzala', 'pmunzala89@siwakadishes.co.ke', 2, 'Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (16, 'Alain', 'Mbeki', 'ambeki98@siwakadishes.co.ke', 2, 'Bartender');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (17, 'Binta', 'Nkurunziza', 'bnkurunziza90@siwakadishes.co.ke', 9, 'Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (18, 'Marie', 'Munyoki', 'mmunyoki56@siwakadishes.co.ke', 3, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (19, 'Njeri', 'Mugisha', 'nmugisha71@siwakadishes.co.ke', 7, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (20, 'Kofi', 'Omondi', 'komondi74@siwakadishes.co.ke', 1, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (21, 'Jacques', 'Odhiambo', 'jodhiambo8@siwakadishes.co.ke', 5, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (22, 'Kiptoo', 'Lumumba', 'klumumba8@siwakadishes.co.ke', 3, 'Bartender');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (23, 'Felix', 'Omondi', 'fomondi8@siwakadishes.co.ke', 2, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (24, 'Adisa', 'Munyui', 'amunyui73@siwakadishes.co.ke', 2, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (25, 'Ifeanyi', 'Hassan', 'ihassan62@siwakadishes.co.ke', 5, 'Waiter');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (26, 'Joseph', 'Munywe', 'jmunywe17@siwakadishes.co.ke', 4, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (27, 'Dayo', 'Malema', 'dmalema29@siwakadishes.co.ke', 1, 'Assistant Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (28, 'Patricia', 'Zuma', 'pzuma81@siwakadishes.co.ke', 9, 'Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (29, 'Jelani', 'Osman', 'josman50@siwakadishes.co.ke', 3, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (30, 'Ngozi', 'Munyuli', 'nmunyuli1@siwakadishes.co.ke', 6, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (31, 'Jelani', 'Adan', 'jadan45@siwakadishes.co.ke', 3, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (32, 'Emmanuel', 'Mutombo', 'emutombo46@siwakadishes.co.ke', 2, 'Waitress');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (33, 'Pierrette', 'Bizimana', 'pbizimana47@siwakadishes.co.ke', 5, 'Assistant Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (34, 'Jean', 'Hassan', 'jhassan59@siwakadishes.co.ke', 4, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (35, 'Binta', 'Hassan', 'bhassan43@siwakadishes.co.ke', 3, 'Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (36, 'Michelle', 'Osman', 'mosman24@siwakadishes.co.ke', 8, 'Waiter');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (37, 'Kiptoo', 'Hussein', 'khussein53@siwakadishes.co.ke', 4, 'Security Guard');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (38, 'Michel', 'Munyua', 'mmunyua48@siwakadishes.co.ke', 5, 'Receptionist');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (39, 'Chinua', 'Bizimana', 'cbizimana52@siwakadishes.co.ke', 4, 'Assistant Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (40, 'Alain', 'Bizimana', 'abizimana18@siwakadishes.co.ke', 8, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (41, 'Chiamaka', 'Kabongo', 'ckabongo68@siwakadishes.co.ke', 10, 'Receptionist');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (42, 'Achieng', 'Munyua', 'amunyua79@siwakadishes.co.ke', 5, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (43, 'Adebayo', 'Mbeki', 'ambeki56@siwakadishes.co.ke', 10, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (44, 'Marie', 'Abdullahi', 'mabdullahi25@siwakadishes.co.ke', 7, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (45, 'Chiamaka', 'Zuma', 'czuma63@siwakadishes.co.ke', 3, 'Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (46, 'Alain', 'Mutombo', 'amutombo9@siwakadishes.co.ke', 6, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (47, 'Adisa', 'Mbeki', 'ambeki13@siwakadishes.co.ke', 8, 'Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (48, 'Jelani', 'Nkurunziza', 'jnkurunziza17@siwakadishes.co.ke', 7, 'Waitress');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (49, 'Jacques', 'Abdi', 'jabdi7@siwakadishes.co.ke', 2, 'Host');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (50, 'Bongani', 'Kabila', 'bkabila97@siwakadishes.co.ke', 6, 'Waiter');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (51, 'Jelani', 'Osman', 'josman62@siwakadishes.co.ke', 4, 'Assistant Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (52, 'Achieng', 'Mwangi', 'amwangi49@siwakadishes.co.ke', 9, 'Security Guard');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (53, 'Kofi', 'Muthoni', 'kmuthoni80@siwakadishes.co.ke', 8, 'Security Guard');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (54, 'Joseph', 'Zuma', 'jzuma48@siwakadishes.co.ke', 8, 'Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (55, 'Ebele', 'Mwangi', 'emwangi77@siwakadishes.co.ke', 5, 'Host');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (56, 'Chinua', 'Mandela', 'cmandela9@siwakadishes.co.ke', 10, 'Bartender');
UPDATE siwaka_dishes.employee SET reportsTo = 51 WHERE employeeNumber = 4;
UPDATE siwaka_dishes.employee SET reportsTo = 17 WHERE employeeNumber = 9;
UPDATE siwaka_dishes.employee SET reportsTo = 3 WHERE employeeNumber = 20;
UPDATE siwaka_dishes.employee SET reportsTo = 33 WHERE employeeNumber = 27;
UPDATE siwaka_dishes.employee SET reportsTo = 27 WHERE employeeNumber = 7;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 14;
UPDATE siwaka_dishes.employee SET reportsTo = 12 WHERE employeeNumber = 15;
UPDATE siwaka_dishes.employee SET reportsTo = 54 WHERE employeeNumber = 16;
UPDATE siwaka_dishes.employee SET reportsTo = 15 WHERE employeeNumber = 23;
UPDATE siwaka_dishes.employee SET reportsTo = 33 WHERE employeeNumber = 24;
UPDATE siwaka_dishes.employee SET reportsTo = 28 WHERE employeeNumber = 32;
UPDATE siwaka_dishes.employee SET reportsTo = 28 WHERE employeeNumber = 49;
UPDATE siwaka_dishes.employee SET reportsTo = 15 WHERE employeeNumber = 3;
UPDATE siwaka_dishes.employee SET reportsTo = 33 WHERE employeeNumber = 18;
UPDATE siwaka_dishes.employee SET reportsTo = 54 WHERE employeeNumber = 22;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 29;
UPDATE siwaka_dishes.employee SET reportsTo = 3 WHERE employeeNumber = 31;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 35;
UPDATE siwaka_dishes.employee SET reportsTo = 54 WHERE employeeNumber = 45;
UPDATE siwaka_dishes.employee SET reportsTo = 17 WHERE employeeNumber = 6;
UPDATE siwaka_dishes.employee SET reportsTo = 27 WHERE employeeNumber = 12;
UPDATE siwaka_dishes.employee SET reportsTo = 15 WHERE employeeNumber = 26;
UPDATE siwaka_dishes.employee SET reportsTo = 15 WHERE employeeNumber = 34;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 37;
UPDATE siwaka_dishes.employee SET reportsTo = 39 WHERE employeeNumber = 39;
UPDATE siwaka_dishes.employee SET reportsTo = 12 WHERE employeeNumber = 51;
UPDATE siwaka_dishes.employee SET reportsTo = 39 WHERE employeeNumber = 10;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 21;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 25;
UPDATE siwaka_dishes.employee SET reportsTo = 33 WHERE employeeNumber = 33;
UPDATE siwaka_dishes.employee SET reportsTo = 39 WHERE employeeNumber = 38;
UPDATE siwaka_dishes.employee SET reportsTo = 28 WHERE employeeNumber = 42;
UPDATE siwaka_dishes.employee SET reportsTo = 17 WHERE employeeNumber = 55;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 8;
UPDATE siwaka_dishes.employee SET reportsTo = 54 WHERE employeeNumber = 11;
UPDATE siwaka_dishes.employee SET reportsTo = 33 WHERE employeeNumber = 30;
UPDATE siwaka_dishes.employee SET reportsTo = 3 WHERE employeeNumber = 46;
UPDATE siwaka_dishes.employee SET reportsTo = 28 WHERE employeeNumber = 50;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 2;
UPDATE siwaka_dishes.employee SET reportsTo = 17 WHERE employeeNumber = 19;
UPDATE siwaka_dishes.employee SET reportsTo = 54 WHERE employeeNumber = 44;
UPDATE siwaka_dishes.employee SET reportsTo = 54 WHERE employeeNumber = 48;
UPDATE siwaka_dishes.employee SET reportsTo = 51 WHERE employeeNumber = 36;
UPDATE siwaka_dishes.employee SET reportsTo = 28 WHERE employeeNumber = 40;
UPDATE siwaka_dishes.employee SET reportsTo = 33 WHERE employeeNumber = 47;
UPDATE siwaka_dishes.employee SET reportsTo = 28 WHERE employeeNumber = 53;
UPDATE siwaka_dishes.employee SET reportsTo = 51 WHERE employeeNumber = 54;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 1;
UPDATE siwaka_dishes.employee SET reportsTo = 27 WHERE employeeNumber = 5;
UPDATE siwaka_dishes.employee SET reportsTo = 12 WHERE employeeNumber = 13;
UPDATE siwaka_dishes.employee SET reportsTo = 54 WHERE employeeNumber = 17;
UPDATE siwaka_dishes.employee SET reportsTo = 51 WHERE employeeNumber = 28;
UPDATE siwaka_dishes.employee SET reportsTo = 3 WHERE employeeNumber = 52;
UPDATE siwaka_dishes.employee SET reportsTo = 45 WHERE employeeNumber = 41;
UPDATE siwaka_dishes.employee SET reportsTo = 33 WHERE employeeNumber = 43;
UPDATE siwaka_dishes.employee SET reportsTo = 12 WHERE employeeNumber = 56;

/*!40000 ALTER TABLE `employee` ENABLE KEYS */;
UNLOCK TABLES;